apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  template:
    spec:
      containers:
        - name: spring-petclinic
          image: devops.nrepositorydev.nus.edu.sg/java/spring-petclinic:latest